### ISSUE TITLE
great work！documentation please

### ISSUE THREAD

**Issue by eisneim** [stanford-futuredata/noscope#1]
read the noscope [article](http://dawn.cs.stanford.edu/2017/06/22/noscope/) it's a good idea to add a difference detector on top of Object Detector since my project uses the scene cut detection to reduce the computation but on the other hand losing many important frames.

**Comment by tbfly** [comment]
Read the f**king code?:)

**Comment by ddkang** [comment]
Thank you for the interest - we will be updating the code and writing some documentation soon.

**Comment by zzzzzz0407** [comment]
hello，i’m also interested in this ,but i do not know how to run it ,can you teach me ?Thanks

**Comment by Yepman0620** [comment]
we are still waiting for the README for this project.Thank you
