### ISSUE TITLE
2 errors detected in the compilation of "/tmp/tmpxft_00016431_00000000-10_yolo.cu.compute_52.cpp1.ii".

### ISSUE THREAD

**Issue by CherryLLL** [stanford-futuredata/noscope#13]
I’m having the following issue when running the bazel build -c opt --copt=-mavx2 --config=cuda noscope
INFO: From Compiling tensorflow/noscope/darknet/src/yolo.cu.cc:
tensorflow/noscope/darknet/src/yolo.cu.cc(36): error: namespace "std" has no member "runtime_error"

tensorflow/noscope/darknet/src/yolo.cu.cc(57): error: namespace "std" has no member "runtime_error"

2 errors detected in the compilation of "/tmp/tmpxft_00016431_00000000-10_yolo.cu.compute_52.cpp1.ii".
ERROR: /home/five/PycharmProjects/chenglin/dataset/IPIU/tensorflow-noscope/tensorflow/noscope/darknet/BUILD:10:1: output 'tensorflow/noscope/darknet/_objs/yolo_gpu/tensorflow/noscope/darknet/src/yolo.cu.o' was not created.
ERROR: /home/five/PycharmProjects/chenglin/dataset/IPIU/tensorflow-noscope/tensorflow/noscope/darknet/BUILD:10:1: not all outputs were created or valid.
Target //tensorflow/noscope:noscope failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.297s, Critical Path: 7.96s

Has anyone seen this error before? Please help me,Thank you

**Comment by ddkang** [comment]
Please use g++ version 5.4 or later.
