### ISSUE TITLE
Analysis of target '//tensorflow/noscope:noscope' failed; build aborted.

### ISSUE THREAD

**Issue by zzzzzz0407** [stanford-futuredata/noscope#14]
when i run the command: bazel build -c opt --copt=-mavx2 --config=cuda noscope,i meet the issue,and i do not know how to fix it ,can you help me?thanks!
![image](https://user-images.githubusercontent.com/27133144/29393972-e3adcdc8-8339-11e7-94a9-c4f0fe39d4fe.png)

**Comment by ddkang** [comment]
https://github.com/stanford-futuredata/noscope#setting-up-the-inference-engine
As described here, you will need to point the BUILD to the correct OpenCV path and add the OpenCV path to your environmental variables.

The lines are here: https://github.com/stanford-futuredata/tensorflow-noscope/blob/speedhax/tensorflow/noscope/BUILD#L20
