### ISSUE TITLE
I can't find a way to produce the train_{Start_index}_{end_index}.csv

### ISSUE THREAD

**Issue by sixtytwosecond** [stanford-futuredata/noscope#16]
As the training file is required in noscope_optimizer.py, I can not find a way to produce the file. Can you please give me some hints? Thank you

Closed: I found out that my GPU doesn't support AVX2

**Comment by chengangfzu** [comment]
Does it the machine memory need at least 300+GB memory?

**Comment by sixtytwosecond** [comment]
Hello,

Thank you for pointing out this. Unfortunately 300GB+ is way too far from
what I have now :/
