### ISSUE TITLE
Any visualizing script for video files?

### ISSUE THREAD

**Issue by Arsey** [stanford-futuredata/noscope#19]
I was looking into the scripts and hope that I can find there something that could help to visualize testing results (draw bounding boxes on frames just like in the article on that GIFs animations), but haven't found it. Is there such a tool in the source code or not?

**Comment by ddkang** [comment]
There is: https://github.com/stanford-futuredata/noscope/blob/master/noscope/Visualizer.py

**Comment by Arsey** [comment]
Thank you!!!

**Comment by Arsey** [comment]
@ddkang btw I was more curious about test results visualization. is it possible?

**Comment by ddkang** [comment]
Since the test results are in currently the binary classification task, we didn't see a need to visualize the results. We have some experiments with bounding boxes in the works though and we'll likely publish a script for the test results then.

**Comment by Arsey** [comment]
I see.
