### ISSUE TITLE
ValueError: Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=3

### ISSUE THREAD

**Issue by zzzzzz0407** [stanford-futuredata/noscope#26]
when i run the ./run.sh 
it appers that
![image](https://user-images.githubusercontent.com/27133144/30407422-bd1f5300-992a-11e7-9268-9b26262296ec.png)
I think that our input's ndim should be 3 but it just tell me it expected 4 ,and throw the error , i do not know what to do
what is more, even  i have comment the coral-reef-long part in run.sh
when i run the script,it still appear like this:
![image](https://user-images.githubusercontent.com/27133144/30407547-4de0bb86-992b-11e7-9ef5-33a6653c0d62.png)
please help me!

**Comment by ddkang** [comment]
run.sh requires all prior steps to work. I believe you are using either the wrong version of Keras or the wrong backend. Please check this and rerun.
