### ISSUE TITLE
No such file or directory:train_918000_1836000.csv

### ISSUE THREAD

**Issue by zzzzzz0407** [stanford-futuredata/noscope#27]
Firstly, thanks a lot for updating your tutorial in time , and i follow your steps which you required.
Everything seems good until the error appears:
![image](https://user-images.githubusercontent.com/27133144/30413739-80d6886e-9952-11e7-95cc-a66910dc6b27.png)
and in that directory i only to find as following:
![image](https://user-images.githubusercontent.com/27133144/30413767-b1413af8-9952-11e7-8b8e-7c03232cccda.png)
it generate the train_918000_1836000.log but no train_918000_1836000.csv
I do not know where the problem is,can you help me?
(PS:for the mp4 is too large, i just cut it to 3000 frames and i also changge the NUM_FRAMES="3000")

**Comment by ddkang** [comment]
You will need the full mp4 to run the script.

**Comment by zzzzzz0407** [comment]
Even when I use the full jackson-town-square.mp4 ,it still appears the same issue.
i just see the definition of train_csv_filename in noscope_motherdog.py like this:
![image](https://user-images.githubusercontent.com/27133144/30463922-2e046de0-9a01-11e7-9b74-cf2cab408b41.png)
but i do not see the code that generate train_csv_filename, can you figure it out for me?
Thanks very much!

**Comment by ddkang** [comment]
Please delete any files/folders in the experiments subdirectory and re-run the script with the full mp4.

**Comment by zzzzzz0407** [comment]
I have delete all the files/folders in the experiments , cnn-avg and cnn-models ,and re-run the full  mp4, but the same issue come back!!! i am so sad ! Can you figure it out ?
![image](https://user-images.githubusercontent.com/27133144/30464846-82925df4-9a06-11e7-8c42-6aeb45c5caa9.png)
besides, I want to know the code where is to generate the train_csv_filename

**Comment by ddkang** [comment]
The folders are necessary. Please re-create them and only delete t he _contents_.

I cannot debug without the full log. Please paste the full log.

**Comment by zzzzzz0407** [comment]
I do not delete the folders only delete the contents ,and my dircetorys list is
![image](https://user-images.githubusercontent.com/27133144/30466698-38da37a2-9a12-11e7-88ab-71e7361894a8.png)

![image](https://user-images.githubusercontent.com/27133144/30466353-cc2d7fa8-9a0f-11e7-998b-c285062c111b.png)
and following is the full log:

[noscope.txt](https://github.com/stanford-futuredata/noscope/files/1305268/noscope.txt)

sorry to bother you often ,thank you very much. Best wishes!

**Comment by ddkang** [comment]
Please cat the log files in this directory:
/home/zhangrf/reborn/data/experiments/coral-reef-long/train/coral-reef-long_convnet_32_32_1.pb-non_blocked_mse.src/

**Comment by zzzzzz0407** [comment]
Thanks firstly，but when i pip install protobuf==2.6.1 and uninstall the 3.4.1 manually, the tensorflow can not work, i re-install the tensorflow but it will automaticlly update the protobuf to 3.4.1,i do not know what to do!
And i would liake to kown if the tensorflow have installed in tensorflow-noscope that i do not have to install myself?

**Comment by zzzzzz0407** [comment]
I can not generate the train_918000_1836000.csv in related directory.
in my jackson-town-square_convnet_128_32_0.pb-non_blocked_mse.src/train_918000_1836000.log, it appears:
![image](https://user-images.githubusercontent.com/27133144/30480329-d325953e-9a4b-11e7-8a34-b9c429a96923.png)
it show me my protobuf version is 3.2.0
but when i use the command: protoc --version
it shows this: libprotoc 2.6.1
when i use the command: pip show protobuf
it shows this:
![image](https://user-images.githubusercontent.com/27133144/30480446-4fec7bfa-9a4c-11e7-8c3e-134bee3f3140.png)
I can not figure out which verison do i have.And i try to delete the protobuf==3.4.0 and install the protobuf==2.6.1 ,then tensorflow can not work well, i do not know what to do ,can you help me?
( PS: all this is in anaconda's virtual environment，and i install or delete the protobuf use the conda command)

**Comment by ddkang** [comment]
tensorflow-noscope requires a specific version of protobuf unrelated to your conda environment. You'll need to match what you have installed with what is linked.

**Comment by zzzzzz0407** [comment]
Can you teach me how to link it? I have try many method from online but all failed...

**Comment by ddkang** [comment]
Due to resource constraints, I can only help with NoScope specific issues. We are in the process of reworking parts of NoScope, so I would recommend waiting until the next release.
