### ISSUE TITLE
Run noscope got error

### ISSUE THREAD

**Issue by janhuang6** [stanford-futuredata/noscope#32]
I have installed tensorflow-noscope and noscope by following the instruction. When I run 
noscope/example/run.sh

It complained:

ImportError: No module named noscope
ImportError: No module named tensorflow

So what did I miss to have python finds noscope and tensorflow?

Thanks,
Jan

**Comment by ddkang** [comment]
Unfortunately I've never seen this error. If you're using a virtual environment, please activate it before running the script.

**Comment by janhuang6** [comment]
I found the fix. That was to downgrade tensorflow from 1.4 to 0.12

**Comment by janhuang6** [comment]
This issue is closed with above mentioned fix.
