### ISSUE TITLE
To understand NoScope

### ISSUE THREAD

**Issue by janhuang6** [stanford-futuredata/noscope#33]
I finally got NoScope running on my Linux with 2 GPUs. To help me understand NoScope better, I have the following questions:

1. For NoScope results, what do those folders "0.0", "0.01", "0.02", ..."0.1", "0.25" mean? How to understand summary.csv?
2. Is the small specialized model the same NN as the reference model but just with less layers? Does NoScope uses any of the traditional model from OpenCV?
3. What is NoScope's software architecture?
4. How to test the optimized performance improvement over reference model, or over the traditional OpenCV?
5. Is there a way to adjust the optimization engine? For instance, can I turn off the optimization?

Thanks!
Jan

**Comment by ddkang** [comment]
Thank you for the interest!

For the first question, those are the results at various error rates. summary.csv collects the results.

You can find the answer to most of the other questions in our paper: http://www.vldb.org/pvldb/vol10/p1586-kang.pdf

**Comment by janhuang6** [comment]
Thank you for the input. This issue can be closed now.
