### ISSUE TITLE
Use my own video to run NoScope

### ISSUE THREAD

**Issue by janhuang6** [stanford-futuredata/noscope#36]
First my video TimeSquare.mp4 is 29 minutes, is that long enough for NoScope study?
How to create the TimeSquare.csv required by NoScope?

Thanks!

**Comment by ddkang** [comment]
All of our experiments used at least 8 hours of training video, but you are welcome to experiment with less.

You can create the necessary training data using yolo_standalone

**Comment by janhuang6** [comment]
Do you have the URL for yolo_standalone? or where to get it? 

Thanks!

**Comment by sxhexe** [comment]
I think you can get it from compiling darknet at tensorflow-noscope/tensorflow/noscope/darknet.

**Comment by janhuang6** [comment]
Thank you for the input. This issue can be closed now.
