### ISSUE TITLE
Is this project under developing or ready to use? 

### ISSUE THREAD

**Issue by GBJim** [stanford-futuredata/noscope#4]
Hi all

Just found the repo from the original publication. I am wondering if this project is ready to test or demo. It seems like there is no documentation and there are no commits in the last four months.

**Comment by aktiger** [comment]
Same question. Are there any instructions on how to run the demo?

**Comment by chengangfzu** [comment]
Hi Jim，
I am interesting in this GitHub  project.It seems that only the paper was published in the arvix!

**Comment by ddkang** [comment]
Thank you for the interest - we will be updating the code and writing some documentation soon. All the code to reproduce the experiments in the paper are available now.
