### ISSUE TITLE
How to understand YOLO_LABELS in noscope_motherdog.py

### ISSUE THREAD

**Issue by janhuang6** [stanford-futuredata/noscope#40]
I see this in noscope_motherdog.py:

YOLO_LABELS["coral-reef-long"] = (
        0,
        [("coral-reef-long_convnet_32_32_1.pb", None),
         ("coral-reef-long_convnet_32_32_2.pb", None),],
        648000 + 1188000,
        1188000,
        648000 + 1188000 * 2,
        1188000
)

So what do those numbers mean? Is there a document explaining those?
I really need to understand those so I can add my own 
YOLO_LABELS["my-video"] session with the correct numbers to have Yolo process my video.

Right now, Yolo is not processing my video correctly because those numbers are not setup right.

**Comment by janhuang6** [comment]
I found the answer. The meanings are:
0	means “yolo_label_num”
[("coral-reef-long_convnet_32_32_1.pb", None),
         ("coral-reef-long_convnet_32_32_2.pb", None),] is the pipelines
        648000 + 1188000 is the TRAIN_START_IDX
        1188000 is the TRAIN_LEN,
        648000 + 1188000 * 2 is the TEST_START_IDX, 
        1188000 is the TEST_LEN

**Comment by sxhexe** [comment]
@janhuang6 Is pipeline just the cnn model? Why is there only two instead of all the 12 CNN's they've trained? 
Also, do you know how they index the videos? I thought there were only 1188000 frames, and 648000 + 1188000 would be out of range.
