### ISSUE TITLE
Updated dataset link?

### ISSUE THREAD

**Issue by mk-hasan** [stanford-futuredata/noscope#46]
I am trying to download the dataset but the given link is not working for me? anyone has updated link. it would be nice to have it for experiment purpose. 
Thank You 

Error: 
(tfg) [root@pinky csv]# wget https://storage.googleapis.com/noscope-data/videos/coral-reef-long.mp4
--2019-07-11 11:47:41--  https://storage.googleapis.com/noscope-data/videos/coral-reef-long.mp4
Resolving storage.googleapis.com (storage.googleapis.com)... 2a00:1450:4001:817::2010, 172.217.21.208
Connecting to storage.googleapis.com (storage.googleapis.com)|2a00:1450:4001:817::2010|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2019-07-11 11:47:42 ERROR 400: Bad Request.

**Comment by ddkang** [comment]
Thank you for the interest in NoScope.

Unfortunately due to the cost of hosting data, we turned on user pays for download. Please sign in to GCP and use gsutil to download the files.

**Comment by ShanrenLi** [comment]
> Thank you for the interest in NoScope.
> 
> Unfortunately due to the cost of hosting data, we turned on user pays for download. Please sign in to GCP and use gsutil to download the files.

How to do that?

**Comment by ddkang** [comment]
https://drive.google.com/drive/folders/1znFWgDNH_rxof-ZTYHd_gwZR8iwY771t?usp=sharing

The data is being uploaded here.
