### ISSUE TITLE
Access denied to noscope-data

### ISSUE THREAD

**Issue by LakeCarrot** [stanford-futuredata/noscope#47]
Hi,

I tried to download the dataset using `gsutil` , below is the bash scripts I have.
```
gsutil -u downloadtest-249815 cp gs://noscope-data/csvs-yolo/coral-reef-long.csv . 
```
However, I got the following error message,
```
AccessDeniedException: 403 XXX@gmail.com does not have storage.objects.list access to noscope-data.
```
I wonder is there anything wrong with my method? Or do I need to first get permission from somewhere else before downloading the related dataset?

Thanks,
Bo

**Comment by ddkang** [comment]
Please try again, there was an issue with GCP on our end.

**Comment by LakeCarrot** [comment]
> Please try again, there was an issue with GCP on our end.

It works now. Thanks!

**Comment by chenzhao** [comment]
Hi, I think this issue is still there.  I just tried to download with my gcp account and got the same error. Any suggestions? Thanks.

➜  ~ gsutil -u videoacc cp gs://noscope-data/csvs-yolo/coral-reef-long.csv .
AccessDeniedException: 403 xxxx@gmail.com does not have storage.objects.list access to noscope-data.

**Comment by ddkang** [comment]
I've confirmed that https://storage.googleapis.com/noscope-data/csvs-yolo/coral-reef-long.csv is public (user pays). You may need to enable a billing account on your end.

**Comment by ddkang** [comment]
If you are unable to attach a billing account, please email me separately and I can arrange for a download.

**Comment by chenzhao** [comment]
> I've confirmed that https://storage.googleapis.com/noscope-data/csvs-yolo/coral-reef-long.csv is public (user pays). You may need to enable a billing account on your end.

The GCP error message is kind of misleading. It is OK with a billing account. Thanks : )
