### ISSUE TITLE
AccessDeniedException: 403 The project to be billed is associated with a closed billing account.

### ISSUE THREAD

**Issue by wtx8887** [stanford-futuredata/noscope#48]
I tried to download the dataset using **gsutil**
I have opened a new google cloud account. And I can create a bucket with the command:
  `gsutil -u download-255905 mb gs://wtx8887-download/`

However, when I want to download the dataset, (using the bash scripts like #47 )
  `gsutil -u download-255905 cp gs://noscope-data/csvs-yolo/coral-reef-long.csv . `

I faced issue as below,
  `AccessDeniedException: 403 The project to be billed is associated with a closed billing account.`

I checked my account, its Statu was **Active**. 
I wonder that is there anything wrong with my method?

Thanks.

**Comment by ddkang** [comment]
Please check back in a coupe of weeks, there's an issue with our GCP account. If you need the CSV immediately please directly email me.
