### ISSUE TITLE
Downloading dataset

### ISSUE THREAD

**Issue by pashazgit** [stanford-futuredata/noscope#49]
I am trying to use GCP and gsutil to download the dataset but I couldn't find any instructions on how to do that. I already enabled the billing account on GCP and when I am trying this command `gsutil -u enduring-maxim-269304 cp gs://noscope-data/csvs-yolo/coral-reef-long.csv ~/Downloads/noscope-data`, it gives me this error 'AccessDeniedException: 403 pasha.current@gmail.com does not have storage.objects.list access to noscope-data'. Can you please provide some basic instructions on how to download them.

Bests
Thanks

**Comment by ddkang** [comment]
Do you have a credit card attached to your account?

**Comment by pashazgit** [comment]
Yes, I do.

**Comment by dnola** [comment]
Same issue here!

**Comment by pashazgit** [comment]
Kindly, may I follow up on my request. I wanted to know how I can access the dataset.
Thanks.

**Comment by ddkang** [comment]
The data is being uploaded to Google drive: https://drive.google.com/drive/folders/1znFWgDNH_rxof-ZTYHd_gwZR8iwY771t?usp=sharing

I will update the README
