### ISSUE TITLE
AttributeError: 'module' object has no attribute 'YOLO'

### ISSUE THREAD

**Issue by aktiger** [stanford-futuredata/noscope#5]
when i run VUSELabeler.py，it says no YOLO attribut, it seems that the YOLO class is missing under noscop dir:

`ubuntu@XP1:~/cvs/noscope$ python scripts/VUSELabeler.py 
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "scripts/VUSELabeler.py", line 85, in <module>
    main()
  File "scripts/VUSELabeler.py", line 79, in main
    args.yolo_dir, args.start_from)
  File "scripts/VUSELabeler.py", line 38, in label_video
    yolo_dir + '/cfg/coco.data')
  File "scripts/VUSELabeler.py", line 15, in __init__
    self.YOLO = noscope.YOLO(config_filename, weights_filename, data_config)
AttributeError: 'module' object has no attribute 'YOLO'
`

**Comment by ddkang** [comment]
Please use yolo_standalone to generate labels:
https://github.com/ddkang/darknet/tree/yolo_standalone
