### ISSUE TITLE
Why is it called NoScope?

### ISSUE THREAD

**Issue by GBJim** [stanford-futuredata/noscope#7]
Hi all:
After reading the paper, I still don't know why this framework is called **NoScope.**
Is it some kind of abbreviation?

**Comment by ddkang** [comment]
We drew inspiration from a world leader in deep learning: https://github.com/pjreddie/darknet/blob/master/src/dropout_layer_kernels.cu#L11

Also: http://www.urbandictionary.com/define.php?term=no%20scope
